name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Display the path
      run: |
        cd ${{github.workspace}}/az-login-workflow
        pwd
        ls -lrt
    
