name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Display the path
      run: 
        Install-Module -Name Az
        Import-Module -Name Az
        Get-AzResourceGroup
      shell: pwsh 
    
